// Generated by tools/build-voice-lexicon.js from dataset/Viet74K.txt. Do not edit.
// Syllables that sound like one spoken number word -> that word (tone marks removed).
(function (G) {
  'use strict';
  G.voiceLexicon = 'bong:bon cam:tram cham:tram chinh:chin khon:khong moc:mot ne:le nhe:le nhin:linh nhinh:linh nin:linh ninh:linh trinh:chin xau:sau'.split(' ').reduce((m, p) => { const [a, b] = p.split(':'); m[a] = b; return m; }, {});
})(window.Gomoku = window.Gomoku || {});
